import type { ApplicationStatus } from '@/components/ui/status.badge';

const STATUS_NORMALIZE_MAP: Record<string, ApplicationStatus> = {
  DRAFT: 'DRAFT',
  BORRADOR: 'DRAFT',
  PENDING_SECRETARY: 'PENDING_SECRETARY',
  PENDIENTE_SECRETARIA: 'PENDING_SECRETARY',
  OBSERVED: 'OBSERVED',
  OBSERVADO: 'OBSERVED',
  PENDING_TECHNICIAN: 'PENDING_TECHNICIAN',
  EN_REVISION_TECNICA: 'PENDING_TECHNICIAN',
  EN_REVISION: 'PENDING_TECHNICIAN',
  UNDER_REVIEW: 'PENDING_TECHNICIAN',
  INSPECTION: 'INSPECTION',
  INSPECCION: 'INSPECTION',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDIENTE_PAGO: 'PENDING_PAYMENT',
  PAID: 'PAID',
  PAGADO: 'PAID',
  APPROVED: 'APPROVED',
  APROBADO: 'APPROVED',
  REJECTED: 'REJECTED',
  NEGADO: 'REJECTED',
  RECHAZADO: 'REJECTED',
};

export function normalizeApplicationStatus(status: string): ApplicationStatus {
  return STATUS_NORMALIZE_MAP[status] ?? 'DRAFT';
}
